# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'HH-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'google-ID'

menu:
- {name: 'About', folder: 'pages', file: 'about.html'}
- {name: 'Portfolio', folder: 'pages', file: 'facts.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/Hinahirani'}
- {icon: 'instagram', link: 'https://www.instagram.com/hinahirani4/?hl=en'}
- {icon: 'envelope', link: 'mailto:hinahirani@hotmail.co.uk'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
